"use client";

import { useState } from "react";
import type { CampaignReviewer, ReviewerRole } from "@/lib/constants";

interface Props {
  initialReviewers?: CampaignReviewer[];
}

export default function TeamReviewersEditor({ initialReviewers = [] }: Props) {
  const [reviewers, setReviewers] = useState<CampaignReviewer[]>(initialReviewers);

  const addReviewer = () => {
    setReviewers([
      ...reviewers,
      {
        id: crypto.randomUUID(), // Will be generated by DB or kept as local ID for UI
        user_id: `user-temp-${Date.now()}`, // Temporary for UI
        name: "",
        email: "",
        avatar_url: null,
        role: "reviewer",
        assigned_at: new Date().toISOString(),
      },
    ]);
  };

  const removeReviewer = (index: number) => {
    setReviewers(reviewers.filter((_, i) => i !== index));
  };

  const updateReviewer = <K extends keyof CampaignReviewer>(index: number, field: K, value: CampaignReviewer[K]) => {
    const newReviewers = [...reviewers];
    newReviewers[index] = { ...newReviewers[index], [field]: value };
    setReviewers(newReviewers);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-medium text-[#111827]">Team Reviewers</h3>
        <button
          type="button"
          onClick={addReviewer}
          className="text-sm text-[#2563EB] hover:text-[#1D4ED8]"
        >
          + Add Reviewer
        </button>
      </div>
      <p className="text-sm text-[#6B7280]">
        Assign team members to review candidates and specify their roles.
      </p>

      {reviewers.length === 0 ? (
        <div className="p-4 bg-gray-50 border border-gray-200 border-dashed rounded-lg text-center text-sm text-gray-500">
          No reviewers assigned.
        </div>
      ) : (
        <div className="space-y-3">
          {reviewers.map((reviewer, index) => (
            <div key={index} className="flex items-center gap-3 p-3 bg-white border border-[#D1D5DB] rounded-lg">
              <div className="flex-1">
                <input
                  type="text"
                  placeholder="Full Name"
                  value={reviewer.name}
                  onChange={(e) => updateReviewer(index, "name", e.target.value)}
                  className="w-full text-sm placeholder:text-[#9CA3AF] bg-white border border-[#D1D5DB] focus:border-[#2563EB] outline-none rounded-md px-3 py-1.5 transition-colors"
                  required
                />
              </div>
              <div className="flex-1">
                <input
                  type="email"
                  placeholder="Email Address"
                  value={reviewer.email}
                  onChange={(e) => updateReviewer(index, "email", e.target.value)}
                  className="w-full text-sm placeholder:text-[#9CA3AF] bg-white border border-[#D1D5DB] focus:border-[#2563EB] outline-none rounded-md px-3 py-1.5 transition-colors"
                  required
                />
              </div>
              <div className="w-40">
                <select
                  value={reviewer.role}
                  onChange={(e) => updateReviewer(index, "role", e.target.value as ReviewerRole)}
                  className="w-full text-sm placeholder:text-[#9CA3AF] bg-white border border-[#D1D5DB] focus:border-[#2563EB] outline-none rounded-md px-3 py-1.5 transition-colors"
                >
                  <option value="lead">Lead</option>
                  <option value="reviewer">Reviewer</option>
                  <option value="observer">Observer</option>
                </select>
              </div>
              <button
                type="button"
                onClick={() => removeReviewer(index)}
                className="text-gray-400 hover:text-red-500 flex-shrink-0 ml-1 p-1"
                aria-label="Remove Reviewer"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Hidden input to pass data to Server Action */}
      <input type="hidden" name="reviewers_json" value={JSON.stringify(reviewers)} />
    </div>
  );
}
