blank_issues_enabled: false
contact_links:
  - name: Discuss / question
    url: https://github.com/MatiousCorp/screenr-ai/discussions
    about: For open-ended questions and discussion, please use Discussions instead of an issue.
